Repository Imtjl/1st-year-guide, pull requests merged in 2023-08, with the labels that each got.

#4 :hammer::rocket::books: Huge guide enhancement
  README.md
  icons/bjd.png
  icons/business.png
  icons/c.png
  icons/calculus.png
  icons/databases.png
  icons/discrete_math.svg
  icons/informatics.png
  icons/java.png
  icons/kik.png
  icons/nodes.png
  icons/opd.png
  icons/philosophy.png
  icons/physics.png
  icons/psql.svg
  icons/web.png
Labels: documentation, enhancement

#19 :sparkles: Add references for maxbarsukov's repo
  README.md
Labels: documentation

#22 :books: Fix table of contents problem
  README.md
Labels: documentation

#31 :books: Final version of 1st year guide
  README.md
Labels: documentation, important
